export const MONGODB_URI = process.env.MONGODB_URI;

export const COMPANY_EMAIL = process.env.NEXT_PUBLIC_COMPANY_EMAIL
export const COMPANY_PHONE = process.env.NEXT_PUBLIC_COMPANY_PHONE
export const COMPANY_FB = process.env.NEXT_PUBLIC_COMPANY_FB
export const COMPANY_INSTAGRAM = process.env.NEXT_PUBLIC_COMPANY_INSTAGRAM
export const COMPANY_FULL_NAME = process.env.NEXT_PUBLIC_COMPANY_FULL_NAME
export const COMPANY_SINGLE_NAME = process.env.NEXT_PUBLIC_COMPANY_SINGLE_NAME